# Generated by Django 5.0.6 on 2024-06-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
