USER_ROLE_ADMIN = "Admin"
USER_ROLE_CUSTOMER = "Customer"

USER_ROLE_CHOICES = [
    (USER_ROLE_ADMIN, "Admin"),
    (USER_ROLE_CUSTOMER, "Customer")
]

JWT_COOKIE_KEY = "jwt"

MESSAGE_USER_CREATED_SUCCESSFULLY = "User Created Successfully"
MESSAGE_LOGIN_SUCCESSFUL = "Login successful"
MESSAGE_INVALID_CREDENTIALS = "Invalid Credentials"

